version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis

  service1:
    build: ./service1/.
    image: service1:0.1
    container_name: service1
    ports:
      - 8001:3000
    depends_on:
      - redis

  service2:
    build: ./service2/.
    image: service2:0.1
    container_name: service2
    ports:
      - 8002:3000
    depends_on:
      - redis
